In [1]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv('titanic.csv')
df.sample(10)

       Cabin           Ticket number  Survived
756      NaN           350042      2         0
430      C52           110564      A         1
599      A20         PC 17485      3         1
523      B18           111361      A         1
220      NaN  SOTON/OQ 392089      5         1
348      NaN       C.A. 37671      2         1
12       NaN        A/5. 2151      3         0
9        NaN           237736      A         1
118  B58 B60         PC 17558      3         0
103      NaN             7540      4         0

In [34]:
df['number_numberical'] = pd.to_numeric(df['number'] , errors='coerce' , downcast='integer')

df['number_categorical'] = np.where(df['number_numberical'].isnull() , df['number'] , np.nan )
df.head()

,Cabin,Ticket,number,Survived,number_numberical,number_categorical
0,NaN,A/5 21171,5,0,5.0,NaN
1,C85,PC 17599,3,1,3.0,NaN
2,NaN,STON/O2. 3101282,6,1,6.0,NaN
3,C123,113803,3,1,3.0,NaN
4,NaN,373450,A,0,NaN,A

In [35]:
df['cabin_num'] = df['Cabin'].str.extract(r'(\d+)')

df['Cabin_categorial'] = df['Cabin'].str[0]
df.head()

,Cabin,Ticket,number,Survived,number_numberical,number_categorical,cabin_num,Cabin_categorial
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123,C
4,NaN,373450,A,0,NaN,A,NaN,NaN

In [36]:
df['Ticket_numberical'] =  df['Ticket'].apply(lambda x : x.split()[-1])
df['Ticket_numberical']=  pd.to_numeric(df['Ticket_numberical'] , errors = 'coerce' , downcast = 'integer')
df['Ticket_categorical'] = df['Ticket'].apply(lambda x :x.split()[0])
df['Ticket_categorical'] = np.where(df['Ticket_categorical'].str.isdigit() , np.nan , df['Ticket_categorical'])
df.head()

,Cabin,Ticket,number,Survived,number_numberical,number_categorical,cabin_num,Cabin_categorial,Ticket_numberical,Ticket_categorical
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN,21171.0,A/5
1,C85,PC 17599,3,1,3.0,NaN,85,C,17599.0,PC
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN,3101282.0,STON/O2.
3,C123,113803,3,1,3.0,NaN,123,C,113803.0,NaN
4,NaN,373450,A,0,NaN,A,NaN,NaN,373450.0,NaN