In [3]:
import pandas as pd

In [6]:
data = pd.read_json('train.json')

In [7]:
data.head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [9]:
import json
import pandas as pd

In [10]:
def load_large_file(filepath , chunksize) :
  chunklist = []
  with open(filepath) as f :
    data = json.load(f)
    for i in range(0 , len(data) ,chunksize) :
      chunk = pd.DataFrame(data[i : i+chunksize])
      chunklist.append(chunk)
  return pd.concat(chunklist , axis =0)

In [13]:
data = load_large_file('train.json' , 10000)

In [14]:
data.head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...