In [1]:
import requests
url = "https://streaming-availability.p.rapidapi.com/shows/search/title"
params = {
    "title": "Inception",
    "country": "us"
}

headers = {
    "x-rapidapi-key": "67627dd62bmsh50a825da1d6c7b2p118ea8jsne7451fe08b8a",
    "x-rapidapi-host": "streaming-availability.p.rapidapi.com"
}
response = requests.get(url, headers=headers, params=params)

In [5]:
data = response.json()

In [6]:
import pandas as pd

In [8]:
df = pd.DataFrame(data)
df.head()

,itemType,showType,id,imdbId,tmdbId,title,overview,releaseYear,originalTitle,genres,...,cast,rating,runtime,imageSet,streamingOptions,firstAirYear,lastAirYear,creators,seasonCount,episodeCount
0,show,movie,70,tt1375666,movie/27205,Inception,A thief (Leonardo DiCaprio) steals people's se...,2010.0,Inception,"[{'id': 'adventure', 'name': 'Adventure'}, {'i...",...,"[Leonardo DiCaprio, Joseph Gordon-Levitt, Ken ...",86,148.0,{'verticalPoster': {'w240': 'https://cdn.movie...,"{'us': [{'service': {'id': 'prime', 'name': 'P...",NaN,NaN,NaN,NaN,NaN
1,show,movie,98511,tt6793710,movie/613092,The Crack: Inception,,2019.0,El crack cero,"[{'id': 'crime', 'name': 'Crime'}, {'id': 'dra...",...,"[Carlos Santos, Miguel Ángel Muñoz, Luisa Gava...",57,122.0,{'verticalPoster': {'w240': 'https://cdn.movie...,{},NaN,NaN,NaN,NaN,NaN
2,show,movie,44527,tt1790736,movie/64956,Inception: The Cobol Job,,2010.0,Inception: The Cobol Job,"[{'id': 'action', 'name': 'Action'}, {'id': 'a...",...,[],72,NaN,{'verticalPoster': {'w240': 'https://cdn.movie...,{},NaN,NaN,NaN,NaN,NaN
3,show,series,51158,tt11437496,tv/107600,The Cruise,,NaN,The Cruise,"[{'id': 'action', 'name': 'Action'}, {'id': 'c...",...,"[Hazar Deniz BG, Ezra ELS, Cansu Gamze Durmuş]",47,NaN,{'verticalPoster': {'w240': 'https://cdn.movie...,{},2021.0,2021.0,"[Ezra ELS, Hazar Deniz BG]",1.0,8.0
4,show,series,26635426,tt43662578,tv/334803,Backrooms: INCEPTION,,NaN,Backrooms: INCEPTION,"[{'id': 'drama', 'name': 'Drama'}, {'id': 'hor...",...,[],0,NaN,{'verticalPoster': {'w240': 'https://www.movie...,{},2026.0,2026.0,[Cone Freeman],1.0,6.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   itemType          20 non-null     object
 1   showType          20 non-null     object
 2   id                20 non-null     object
 3   imdbId            20 non-null     object
 4   tmdbId            20 non-null     object
 5   title             20 non-null     object
 6   overview          20 non-null     object
 7   releaseYear       17 non-null     float64
 8   originalTitle     20 non-null     object
 9   genres            20 non-null     object
 10  directors         17 non-null     object
 11  cast              20 non-null     object
 12  rating            20 non-null     int64
 13  runtime           8 non-null      float64
 14  imageSet          20 non-null     object
 15  streamingOptions  20 non-null     object
 16  firstAirYear      3 non-null      float64
 17  lastAirYear       3 non-null      float64
 18  creators          3 non-null      object
 19  seasonCount       3 non-null      float64
 20  episodeCount      3 non-null      float64
dtypes: float64(6), int64(1), object(14)
memory usage: 3.4+ KB

In [11]:
df.isnull().sum()

itemType             0
showType             0
id                   0
imdbId               0
tmdbId               0
title                0
overview             0
releaseYear          3
originalTitle        0
genres               0
directors            3
cast                 0
rating               0
runtime             12
imageSet             0
streamingOptions     0
firstAirYear        17
lastAirYear         17
creators            17
seasonCount         17
episodeCount        17
dtype: int64

In [12]:
df['episodeCount'] = df['episodeCount'].fillna(df['episodeCount'].mean())

In [14]:
df.isnull().sum()

itemType             0
showType             0
id                   0
imdbId               0
tmdbId               0
title                0
overview             0
releaseYear          3
originalTitle        0
genres               0
directors            3
cast                 0
rating               0
runtime             12
imageSet             0
streamingOptions     0
firstAirYear        17
lastAirYear         17
creators            17
seasonCount         17
episodeCount         0
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   itemType          20 non-null     object
 1   showType          20 non-null     object
 2   id                20 non-null     object
 3   imdbId            20 non-null     object
 4   tmdbId            20 non-null     object
 5   title             20 non-null     object
 6   overview          20 non-null     object
 7   releaseYear       17 non-null     float64
 8   originalTitle     20 non-null     object
 9   genres            20 non-null     object
 10  directors         17 non-null     object
 11  cast              20 non-null     object
 12  rating            20 non-null     int64
 13  runtime           8 non-null      float64
 14  imageSet          20 non-null     object
 15  streamingOptions  20 non-null     object
 16  firstAirYear      3 non-null      float64
 17  lastAirYear       3 non-null      float64
 18  creators          3 non-null      object
 19  seasonCount       3 non-null      float64
 20  episodeCount      20 non-null     float64
dtypes: float64(6), int64(1), object(14)
memory usage: 3.4+ KB